---
apiVersion: v1
kind: Service
metadata:
  name: nginx-custom
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: nginx-custom
    app.kubernetes.io/part-of: ingress-nginx
spec:
  selector:
    app.kubernetes.io/name: nginx-custom
    app.kubernetes.io/part-of: ingress-nginx
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: nginx-custom
    app.kubernetes.io/part-of: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-custom
      app.kubernetes.io/part-of: ingress-nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-custom
        app.kubernetes.io/part-of: ingress-nginx
    spec:
      nodeSelector:
        role: frontend
      containers:
      - name: nginx-custom
        image: musmanayub/nginx-custom:v1
        ports:
        - containerPort: 80
