apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-frontend
  template:
    metadata:
      name: admin-pod
      labels:
        app: admin-frontend
    spec:
      nodeSelector: 
        role: frontend
      # tolerations:
      # - key: "dedicated"
      #   operator: "Equal"
      #   value: "fe"
      #   effect: "NoSchedule"    
      containers:
      - image: hshar/admin
        name: container
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - ls
        volumeMounts:
        - name: db-secret
          mountPath: /var/secrets
      volumes: 
      - name: db-secret
        secret:
          secretName: db-secret
---
apiVersion: v1
kind: Service
metadata:
 name: admin-frontend-service
spec:
 ports:
 - targetPort: 80
   port: 80
 selector:
   app: admin-frontend
 type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-frontend
  template:
    metadata:
      name: users-pod
      labels:
        app: users-frontend
    spec:
      # tolerations:
      # - key: "dedicated"
      #   operator: "Equal"
      #   value: "be"
      #   effect: "NoSchedule"
      nodeSelector: 
        role: frontend
      containers:
      - image: hshar/users
        name: container
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
            - ls
        volumeMounts:
        - name: db-secret
          mountPath: /var/secrets
      volumes: 
      - name: db-secret
        secret:
          secretName: db-secret
---

apiVersion: v1
kind: Service
metadata:
 name: users-frontend-service
spec:
 ports:
 - targetPort: 80
   port: 80
 selector:
   app: users-frontend
 type: NodePort
