apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster
  region: us-east-2

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    labels: {role: frontend}
    # taints: 
    #   dedicated: "fe:NoSchedule"
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/aws_id_rsa.pub
  - name: ng-2
    instanceType: t2.micro
    minSize: 1
    maxSize: 1
    desiredCapacity: 1
    labels: {role: backend}
    # taints: 
    #   dedicated: "be:NoSchedule"
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/aws_id_rsa.pub
