apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{file.system.id}}}

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: db-pv
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 1Gi
#   hostPath:
#     path: /var/lib/mysql
#   storageClassName: aws-efs

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db-pvc
# spec:
#   accessModes:
#   - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: aws-efs