kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: db
  labels:
    app: backend
spec:
  containers:
  - name: db-container
    image: hshar/mysql:5.5
    ports:
    - containerPort: 3306
    livenessProbe:
      exec:
        command:
        - ls
    volumeMounts:
    - name: db-secret
      mountPath: "/var/secrets"
  volumes:
  - name: db-secret
    secret:
      secretName: db-secret

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
  - targetPort: 3306
    port: 3306
  selector:
    app: backend
  type: ClusterIP