apiVersion: v1
kind: Secret
metadata: 
  name: mysql
type: Opaque
stringData: 
  password: edureka
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
 name: db-pod
 labels:
   app: backend
spec:
  selector: 
    matchLabels:
      app : db
  serviceName: db
  replicas: 1
  template: 
    metadata: 
      labels:
        app: db
    spec: 
      nodeSelector:
        role: backend
      # tolerations:
      # - key: "dedicated"
      #   operator: "Equal"
      #   value: "be"
      #   effect: "NoSchedule"
      containers:
      - name: db-container
        image: hshar/mysql:5.5
        ports:
        - containerPort: 3306
        livenessProbe:
          exec:
          command:
          - ls
      env: 
      - name: MYSQL_ROOT_PASSWORD
        valueFrom: 
          secretKeyRef: 
            name: mysql
            key: password
      volumeMounts:
      - name: pvol
        mountPath: /var/lib/mysql
    volumes:
    - name: pvol
      persistentVolumeClaim: 
        claimName: efs-claim
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  ports:
  - targetPort: 3306
    port: 3306
  selector:
    app: backend
  clusterIP: None
