apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kube-system
  name: "ingress"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
    kubernetes.io/ingress.class: "nginx"

#    kubernetes.io/ingress.class: alb
  labels:
    app: nginx-ingress
spec:
  rules:
    http:
      paths:
      - path: /admin
        backend:
          serviceName: admin-frontend-service
          servicePort: 80
      - path: /users
        backend:
          serviceName: users-frontend-service
          servicePort: 80
      - path: /
        backend:
          serviceName: users-frontend-service 
          servicePort: 80
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: test-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/add-base-url: "true"
#     nginx.ingress.kubernetes.io/rewrite-target: "/"
# spec:
#   rules:
#   - host: {{host_name}}
#     http:
#       paths:
#       - path: /admin
#         backend:
#           serviceName: admin-frontend-service
#           servicePort: 80
#       - path: /users
#         backend:
#           serviceName: users-frontend-service
#           servicePort: 80
#   backend:
#     serviceName: custom-ingress-err
#     servicePort: 80
